# Sets default memory used for Gradle commands
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties (see https://projects.neoforged.net/neoforged/neoforge)
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.250
loader_version_range=[1,)

## Mod Properties
# The unique mod identifier for the mod fitting regex [a-z][a-z0-9_]{1,63}
mod_id=createcrystallized
mod_name=Create Crystallized
# The license of the mod (see https://choosealicense.com/)
mod_license=MIT
# The mod version (see https://semver.org/)
mod_version=0.0.1
# The group ID for the mod (see https://maven.apache.org/guides/mini/guide-naming-conventions.html)
mod_group_id=com.nasilk.createcrystallized
mod_authors=NA-Silk, Pebbbles
mod_description=Adds new crystal-themed blocks and fluids to extend Create features and recipes

## Dependency version defaults
create_version=6.0.10-280
registrate_version=MC1.21-1.3.0+67
ponder_version=1.0.82
sable_version=2.0.6
sable_companion_version=1.6.0
aeronautics_version=1.3.1
simulated_version=1.3.1
offroad_version=1.3.1
flywheel_version=1.0.6
jei_version=19.27.0.340
